jobs:
  deploy_demo_model:
    account_id: "{{ account_id }}"
    project_id: "{{ project_id }}"
    environment_id: "{{ environment_id }}"
    name: "{{ ENVIRONMENT }} - deploy_demo_model"

    settings:
      threads: 1
      target_name: default

    run_generate_sources: false

    execute_steps:
      - dbt build --select my_first_dbt_model

    generate_docs: false

    schedule:
      cron: "0 0 * * *"

    triggers:
      github_webhook: false
      git_provider_webhook: false
      schedule: false
      on_merge: false

    environment_variables: []
