# testing CICD pipeline
jobs:
  deploy_demo_model:
    account_id: "{{ account_id }}"
    project_id: "{{ project_id }}"
    environment_id: "{{ environment_id }}"
    name: "{{ ENVIRONMENT }} - "

    settings:
      threads: 1
      target_name: default

    execution:
      execute_steps:
        - dbt build --select my_first_dbt_model

    schedule:
      cron: "0 0 * * *"
      timezone: "UTC"

    triggers:
      schedule: false
      github_webhook: false
     fgit_provider_webhook: false
      on_merge: false
