name: Plan for syncing DBT Cloud Jobs

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'jobs/**'

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - run: pip install dbt-jobs-as-code~=0.6.0

      - name: Plan
        run: dbt-jobs-as-code plan jobs/demo_jobs.yml --vars-yml jobs/DEV_vars.yml

        env:
          DBT_API_KEY: ${{ secrets.CDP_DBT_API_KEY }}
          DBT_BASE_URL: "https://xh467.us1.dbt.com"
