name: Sync DBT Cloud Jobs

on:
  push:
    branches:
      - main
    paths:
      - 'jobs/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dbt-jobs-as-code
        run: pip install dbt-jobs-as-code~=0.6.0

      - name: Sync dbt Cloud Jobs
        run: dbt-jobs-as-code sync jobs/demo_jobs.yml --vars-yml jobs/DEV_vars.yml
        env:
          DBT_API_KEY: ${{ secrets.CDP_DBT_API_KEY }}
          DBT_BASE_URL: "https://xh467.us1.dbt.com"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Trigger dbt Job Run
        run: |
          ACCOUNT_ID=70471823540206
          JOB_ID=70471823571037

          echo "Triggering dbt job..."

          RESPONSE=$(curl -s -X POST \
          https://xh467.us1.dbt.com/api/v2/accounts/$ACCOUNT_ID/jobs/$JOB_ID/run/ \
          -H "Authorization: Token $DBT_API_KEY" \
          -H "Content-Type: application/json" \
          --data-raw '{"cause": "Triggered via GitHub Actions pipeline"}')

          echo "API response:"
          echo "$RESPONSE"

          SUCCESS=$(echo "$RESPONSE" | jq -r '.status.is_success')

          if [ "$SUCCESS" != "true" ]; then
            echo "Failed to trigger dbt job"
            exit 1
          fi

          RUN_ID=$(echo "$RESPONSE" | jq -r '.data.id')

          echo "Run ID: $RUN_ID"

          echo "Run URL:"
          echo "https://xh467.us1.dbt.com/#/accounts/$ACCOUNT_ID/runs/$RUN_ID/"
        env:
          DBT_API_KEY: ${{ secrets.CDP_DBT_API_KEY }}
